In [122]:
import tensorflow as tf
print('tensorflow_version',tf.__version__)

tensorflow_version 2.6.0


In [123]:
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0


In [124]:
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Flatten(input_shape=(28,28)),
                                  tf.keras.layers.Dense(128,activation='relu'),
                                  tf.keras.layers.Dropout(0.2),
                                  tf.keras.layers.Dense(10),
                                  #tf.keras.layers.Softmax()
])




In [125]:
predictions=model(x_train[:1]).numpy()
predictions

array([[ 0.45307875, -0.18067646, -0.19675766,  0.07672346, -0.0764754 ,
        -0.04128955, -0.08816738,  0.743087  , -0.32578474,  0.15249586]],
      dtype=float32)

In [126]:
tf.nn.softmax(predictions).numpy()

array([[0.14172971, 0.07520115, 0.0740015 , 0.09727737, 0.08346002,
        0.0864489 , 0.08248989, 0.18941304, 0.06504363, 0.10493477]],
      dtype=float32)

In [127]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [128]:
loss_fn(y_train[:1],predictions).numpy()

2.448202

In [129]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
              )

In [130]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2988 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1450 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1075 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0895 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0767 - accuracy: 0.9758


In [131]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0751 - accuracy: 0.9774


[0.07512661814689636, 0.977400004863739]

In [132]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [133]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.43737232e-08, 1.69305514e-09, 8.69926964e-07, 6.07956572e-05,
        8.48117410e-10, 8.02687872e-09, 1.50895071e-13, 9.99937415e-01,
        7.41350732e-08, 7.04937349e-07],
       [4.61093862e-07, 1.85385783e-04, 9.99805748e-01, 7.46271462e-06,
        8.18607713e-18, 3.04089156e-07, 1.63189888e-08, 3.09639602e-13,
        5.71473151e-07, 4.49231310e-14],
       [3.76966227e-07, 9.97443438e-01, 2.55065825e-04, 8.52417088e-06,
        7.56742229e-05, 1.90395167e-05, 1.34650099e-05, 1.78996741e-03,
        3.92935646e-04, 1.43845944e-06],
       [9.99873757e-01, 1.63440053e-10, 1.20202785e-04, 1.13484777e-08,
        3.54069329e-10, 3.27784193e-07, 4.73150777e-07, 4.59872081e-06,
        8.63529976e-08, 6.83050132e-07],
       [1.06801963e-05, 2.80067125e-09, 4.85387773e-06, 1.92659861e-08,
        9.84663904e-01, 7.62257883e-08, 7.99058398e-07, 4.19386633e-05,
        2.94391157e-07, 1.52774332e-02]], dtype=float32)>